#  Assignment 5

This assignment covers material on matrices, norms, condition numbers and eigensystems. The assignment is due by 5pm on Friday the 17th of April.

The breakdown of the marks is as follows:

Question 0 - [1 mark]  
Question 1 - [7 marks]  
Questino 2 - [6 marks]  
Question 3 - [7 marks]  
Question 4 - [9 marks]  

# Question 0

You should have saved this notebook to your ACM20030-Assignments folder. Now:
- commit the notebook to your local repository
- push the changes to the GitHub

In [1]:
import numpy as np
from numpy import linalg as la
np.set_printoptions(linewidth=200)  # This stops line wrapping of larger matrices

# Question 1 - practice manipulating arrays

This questions asks you write a few functions for manipulating arrays of data

## Q1 a

Write a function that checks if a given $n\times n$ matrix is symmetric. Use only loops and `.shape` function from numpy (do not use any other special numpy functions).

In [2]:
def CheckMatSym(mat):
    s = mat.shape
    cols = s[0]
    rows = s[1]
    print('cols =',cols,' rows=',rows)
    if rows != cols:
        return False
    row = 0
    while row < rows:
        col = 0
        while col < cols:
            if mat[row,col] != mat[col,row]:
                return False
            col += 1
        row += 1
    return True
    

A = np.random.rand(4,6)    
print(A)
print('A',CheckMatSym(A))
B = np.matrix([[1, 2], [3, 4]])
print(B)
print('B',CheckMatSym(B))
C = np.matrix([[1, 2], [2, 1]])
print('C',CheckMatSym(C))


[[0.97510078 0.38914378 0.28906171 0.61120705 0.89528905 0.21175609]
 [0.79750794 0.49888474 0.87134981 0.02441776 0.18424258 0.93877098]
 [0.96889468 0.22072157 0.58652113 0.52497854 0.86421723 0.59254514]
 [0.58469699 0.54624698 0.15267928 0.59401062 0.25262707 0.34935995]]
cols = 4  rows= 6
A False
[[1 2]
 [3 4]]
cols = 2  rows= 2
B False
cols = 2  rows= 2
C True


Test your function on the two matrices below

In [3]:
A = np.random.rand(5,5)
SymMatrix = (A + A.T)/2

In [4]:
CheckMatSym(A)

cols = 5  rows= 5


False

In [7]:
CheckMatSym(SymMatrix)

cols = 5  rows= 5


True

## Q1 b

Write a function to transpose a general $n\times n$ matrix. Do this by writing loops and not using any special functions like `np.transpose()`, `A.T`, or any functions from any other library.

In [9]:
def Transpose(mat):
    s = mat.shape
    cols = s[0]
    rows = s[1]
    print('cols =',cols,' rows=',rows)
    t = np.zeros((rows,cols))
#    t.shape = (rows,cols)
    row = 0
    while row < rows:
        col = 0
        while col < cols:
            t[row,col] = mat[col,row]
            col += 1
        row += 1
    return t
    

Check your code by transposing the below random matrix and checking that $A^T \neq A$ and $(A^T)^T - A = 0$

In [10]:
A = np.random.rand(6,6)
print('A=',A)
print('Transpose of A=',Transpose(A))

#Check A - A Transpose != 0
print('A - A transpose=',Transpose(A) - A)

#Check (𝐴𝑇)𝑇−𝐴=0
ATranA = Transpose(Transpose(A))
print(ATranA - A)

A= [[0.02212919 0.05424751 0.30599125 0.92850429 0.01936638 0.03632392]
 [0.52597009 0.89102456 0.84383243 0.17106303 0.85893771 0.84583767]
 [0.63283701 0.78549147 0.6910634  0.80777537 0.20727573 0.31995497]
 [0.11049195 0.77889702 0.62512484 0.93117962 0.29027954 0.98437235]
 [0.32059164 0.65872836 0.65855017 0.95066902 0.71831774 0.92502683]
 [0.14231186 0.12228262 0.82682393 0.66440647 0.41670616 0.68301955]]
cols = 6  rows= 6
Transpose of A= [[0.02212919 0.52597009 0.63283701 0.11049195 0.32059164 0.14231186]
 [0.05424751 0.89102456 0.78549147 0.77889702 0.65872836 0.12228262]
 [0.30599125 0.84383243 0.6910634  0.62512484 0.65855017 0.82682393]
 [0.92850429 0.17106303 0.80777537 0.93117962 0.95066902 0.66440647]
 [0.01936638 0.85893771 0.20727573 0.29027954 0.71831774 0.41670616]
 [0.03632392 0.84583767 0.31995497 0.98437235 0.92502683 0.68301955]]
cols = 6  rows= 6
A - A transpose= [[ 0.          0.47172258  0.32684576 -0.81801235  0.30122526  0.10598794]
 [-0.47172258  0.      

## Q1c

Write a function that finds the maximum entry in a matrix (where the matrix does not need to be square). Do this by writing loops and not using any special functions like `np.max` or any functions from any other library.

In [11]:
def MaxEntry(mat):
    s = mat.shape
    cols = s[0]
    rows = s[1]
    max = 0
    for row in range(0, rows):
        for col in range(0, cols):
            if ((col == 0) and (row == 0)) or (mat[col,row] > max):
                max = mat[col,row]
    return max


Check your result by comparing to `np.max(A)` for the below random matrix

In [12]:
A = np.random.rand(4,5)
print(A)
print('Max=',MaxEntry(A))
print('np.max=',np.max(A))

[[0.22108674 0.59494943 0.31148849 0.16994533 0.34065896]
 [0.77269397 0.20878821 0.03623942 0.88428907 0.69218887]
 [0.67403724 0.82664147 0.73443919 0.77325749 0.70932828]
 [0.7760173  0.85431776 0.75671395 0.44362564 0.4132251 ]]
Max= 0.8842890732012063
np.max= 0.8842890732012063


# Question 2:  matrix norms

In the lectures we focused on the $L^2$-norm. We also briefly mentioned the $L^1$ and $L^\infty$ norm. Let's look at calculating those as well for a general $m\times n$ matrix.

# Q2a

The $L^1$ norm is given by

$$ \lVert A \rVert_1 = \max_j \sum^m_{i=1} |a_{ij}| $$

i.e., it is the max of the sums of the absolute values of each column. Write a function that computes the $L^1$-norm using only loops. The function should use no special numpy functions except `np.abs()`.

In [13]:
def L1Norm(mat):
    s = mat.shape
    cols = s[0]
    rows = s[1]
    colmax = 0
    for row in range(0, rows):
        colsum = 0;
        for col in range(0, cols):
            ele = mat[col,row]
            if ele < 0:
                ele = -ele
            colsum += ele
        if (row == 0) or (colsum > colmax):
             colmax = colsum
    return colmax
    

Check your result against NumPy's `la.norm(A,1)` function for the following random matrix

In [14]:
A = np.random.rand(3,4)
print(A)
print('L1Norm=',L1Norm(A))
print('la.norm=',la.norm(A,1))

[[0.21090372 0.70817982 0.7054183  0.76282074]
 [0.02804681 0.30036905 0.55013124 0.24197291]
 [0.29245415 0.71088732 0.25538234 0.87706163]]
L1Norm= 1.8818552774139523
la.norm= 1.8818552774139523


## Q2b

The $L^\infty$ norm is given by 

$$\lVert A \rVert_\infty = \max_i \sum_{j=1}^n |a_{ij}|$$

i.e., it is the max of the sums of the absolute values of each row. Write a function that computes the $L^\infty$-norm using only loops and no special numpy functions.

In [15]:
def LInf(mat):
    s = mat.shape
    cols = s[0]
    rows = s[1]
    rowmax = 0
    for col in range(0, cols):
        rowsum = 0;
        for row in range(0, rows):
            ele = mat[col,row]
            if ele < 0:
                ele = -ele
            rowsum += ele
        if (col == 0) or (rowsum > rowmax):
             rowmax = rowsum
    return rowmax
    

Check your result against NumPy's `la.norm(A,np.inf)` function for the following random matrix

In [16]:
A = np.random.rand(3,4)
print(A)
print('LInf=',LInf(A))
print('la.norm(A,np.inf)=',la.norm(A,np.inf))

[[0.20482658 0.63422424 0.06578422 0.43374196]
 [0.58681211 0.89096277 0.00824977 0.04418431]
 [0.71958554 0.86717515 0.91729873 0.95685279]]
LInf= 3.4609122038067177
la.norm(A,np.inf)= 3.4609122038067177


# Question 3: ill-conditions systems of equations

In this question you can use any of NumPy's functions.

## Q3a

Which of the following three matrices, $A1, A2, A3$, are ill-conditioned. State the reason for your conclusion.

In [46]:
A1 = np.array([[0.988746460106, 0.351486109477, 0.024911477532, 0.384039749683],
       [0.282104657306, 0.239884151775, 0.36170151991 , 0.903082266861],
       [0.59333290915 , 0.637178863968, 0.241229214635, 0.685595037901],
       [0.013591747828, 0.917926970364, 0.458689093885, 0.157821121254]])

A2 = np.array([[ 2.852416473483e-01,  3.803483118694e-01,  2.697704226632e-01,  6.810611849029e-01],
       [ 6.622827828376e-01,  6.447943415836e-01,  4.387842058829e-01,  1.530575702376e+00],
       [ 3.672130860703e-01,  8.309522079704e-01,  9.975487474007e-01,  5.678296337101e-01],
       [ 4.036490000599e-01,  6.865978225967e-06,  8.788095913773e-01, -7.150472427928e-02]])

A3 = np.array([[0.131923621844, 0.245316154195, 0.732362341613, 0.957047891764],
       [0.91290446184 , 0.512312007959, 0.391938831444, 0.092509684772],
       [0.648708523652, 0.608576675797, 0.576773587276, 0.065385122929],
       [0.502955480393, 0.084082960221, 0.659487390444, 0.662958739412]])

# Q3b

With $b = [1,2,3,4]$ and $\delta b = [0.1,0,0,0]$ for $A2$ and $A3$ calculate the percentage change in $x$ due to a small change in $b$, i.e., calculate 

$$100\times\frac{\lVert \delta x_i\rVert_2}{\lVert x_i \rVert_2}\quad\text{and}\quad 100\times\frac{\lVert \delta b\rVert_2}{\lVert b \rVert_2}$$

where $(x_i+\delta x_i)  = A_i^{-1}(b+\delta b)$ and $i\in\{2,3\}$.

Which system of equations is more sensitive to small changes in $b$? How could you have guessed this from the answer to the Q3a?

In [10]:
# Answer here
#

# Question 4: eigensystems

In this question we look at finding eigenvalues and eigenvectors

## Q4a

You may use any of NumPy's functions for this sub-question.

Find the eigenvalues and eigenvectors for the below matrix. Print out the eigenvalues sorted by descending value and explicitly show that eigenvalues/eigenvector pairs satisfy $Ax = \lambda x$.

In [50]:
A = np.array([[1,4,5],[4,5,4],[6,7,9]])

# Q4b

Without using NumPy's `la.eig()` (or similar functions), find the 4 eigenvalues and eigenvectors of the following matrix. Hint: Use the power method for the max eigenvalue (given below in `MaxEigenvalue`), the power method applied to the inverse for the smallest eigenvalue, and apply Hotelling's deflation twice to find the second and third eigenvalues/eigenvectors.

In [52]:
A = np.array([[1.935052353404, 0.887037260957, 1.534235483277, 1.370691224125],
       [0.887037260957, 0.81275989158 , 0.610238622918, 0.999150521052],
       [1.534235483277, 0.610238622918, 1.562260333538, 1.007843062517],
       [1.370691224125, 0.999150521052, 1.007843062517, 1.813258814483]])

In [53]:
def MaxEigenvalue(A, err):
    (m,n) = A.shape
    if(m != n):
        print("Matrix must be square")
        return
    x = np.random.rand(m)
    
    lam = 0.1
    lamprev = 1
    while np.abs(1-lam/lamprev) > err:
        p = np.dot(A,x)
        lamprev = lam
        lam = np.max(p)
        x = p/lam
        
    x = x/la.norm(x)
    return (lam,x)

Check your answers against Numpy's results from `la.eig(A)`