#  Assignment 5

This assignment covers material on matrices, norms, condition numbers and eigensystems. The assignment is due by 5pm on Friday the 17th of April.

The breakdown of the marks is as follows:

Question 0 - [1 mark]  
Question 1 - [7 marks]  
Questino 2 - [6 marks]  
Question 3 - [7 marks]  
Question 4 - [9 marks]  

# Question 0

You should have saved this notebook to your ACM20030-Assignments folder. Now:
- commit the notebook to your local repository
- push the changes to the GitHub

In [1]:
import numpy as np
from numpy import linalg as la
np.set_printoptions(linewidth=200)  # This stops line wrapping of larger matrices

# Question 1 - practice manipulating arrays

This questions asks you write a few functions for manipulating arrays of data

## Q1 a

Write a function that checks if a given $n\times n$ matrix is symmetric. Use only loops and `.shape` function from numpy (do not use any other special numpy functions).

In [2]:
def CheckMatSym(mat):
    s = mat.shape
    cols = s[0]
    rows = s[1]
    print('cols =',cols,' rows=',rows)
    if rows != cols:
        return False
    row = 0
    while row < rows:
        col = 0
        while col < cols:
            if mat[row,col] != mat[col,row]:
                return False
            col += 1
        row += 1
    return True
    

A = np.random.rand(4,6)    
print(A)
print('A',CheckMatSym(A))
B = np.matrix([[1, 2], [3, 4]])
print(B)
print('B',CheckMatSym(B))
C = np.matrix([[1, 2], [2, 1]])
print('C',CheckMatSym(C))


[[0.95984068 0.68367203 0.33102053 0.76046285 0.55396334 0.27290116]
 [0.8117619  0.7205994  0.63108069 0.84022481 0.52750107 0.60951675]
 [0.44972118 0.41503033 0.68849505 0.17843501 0.13289349 0.03742895]
 [0.18605037 0.65424076 0.47670471 0.31800542 0.37614922 0.69394066]]
cols = 4  rows= 6
A False
[[1 2]
 [3 4]]
cols = 2  rows= 2
B False
cols = 2  rows= 2
C True


Test your function on the two matrices below

In [3]:
A = np.random.rand(5,5)
SymMatrix = (A + A.T)/2

In [4]:
CheckMatSym(A)

cols = 5  rows= 5


False

In [5]:
CheckMatSym(SymMatrix)

cols = 5  rows= 5


True

## Q1 b

Write a function to transpose a general $n\times n$ matrix. Do this by writing loops and not using any special functions like `np.transpose()`, `A.T`, or any functions from any other library.

In [6]:
def Transpose(mat):
    s = mat.shape
    cols = s[0]
    rows = s[1]
    print('cols =',cols,' rows=',rows)
    t = np.zeros((rows,cols))
#    t.shape = (rows,cols)
    row = 0
    while row < rows:
        col = 0
        while col < cols:
            t[row,col] = mat[col,row]
            col += 1
        row += 1
    return t
    

Check your code by transposing the below random matrix and checking that $A^T \neq A$ and $(A^T)^T - A = 0$

In [7]:
A = np.random.rand(6,6)
print('A=',A)
print('Transpose of A=',Transpose(A))

#Check A - A Transpose != 0
print('A - A transpose=',Transpose(A) - A)

#Check (𝐴𝑇)𝑇−𝐴=0
ATranA = Transpose(Transpose(A))
print(ATranA - A)

A= [[0.54813906 0.89277369 0.31163987 0.24466411 0.8047924  0.74165555]
 [0.001962   0.57256765 0.525064   0.01002904 0.48652451 0.62274451]
 [0.37938504 0.25360631 0.01768344 0.31796383 0.79550079 0.20959964]
 [0.29184913 0.06942022 0.02710317 0.98153022 0.3713965  0.63631841]
 [0.95418871 0.63307301 0.26832472 0.31768018 0.30405801 0.834741  ]
 [0.19546636 0.12615883 0.19122319 0.59945754 0.65470353 0.55584935]]
cols = 6  rows= 6
Transpose of A= [[0.54813906 0.001962   0.37938504 0.29184913 0.95418871 0.19546636]
 [0.89277369 0.57256765 0.25360631 0.06942022 0.63307301 0.12615883]
 [0.31163987 0.525064   0.01768344 0.02710317 0.26832472 0.19122319]
 [0.24466411 0.01002904 0.31796383 0.98153022 0.31768018 0.59945754]
 [0.8047924  0.48652451 0.79550079 0.3713965  0.30405801 0.65470353]
 [0.74165555 0.62274451 0.20959964 0.63631841 0.834741   0.55584935]]
cols = 6  rows= 6
A - A transpose= [[ 0.         -0.89081169  0.06774517  0.04718502  0.14939632 -0.54618919]
 [ 0.89081169  0.      

## Q1c

Write a function that finds the maximum entry in a matrix (where the matrix does not need to be square). Do this by writing loops and not using any special functions like `np.max` or any functions from any other library.

In [8]:
def MaxEntry(mat):
    s = mat.shape
    cols = s[0]
    rows = s[1]
    max = 0
    for row in range(0, rows):
        for col in range(0, cols):
            if ((col == 0) and (row == 0)) or (mat[col,row] > max):
                max = mat[col,row]
    return max


Check your result by comparing to `np.max(A)` for the below random matrix

In [9]:
A = np.random.rand(4,5)
print(A)
print('Max=',MaxEntry(A))
print('np.max=',np.max(A))

[[0.07951192 0.78435091 0.77108017 0.19404516 0.98088884]
 [0.02643235 0.49372812 0.24665752 0.11725343 0.90267395]
 [0.69841124 0.51632601 0.67605749 0.91630225 0.9960726 ]
 [0.29097314 0.17017639 0.72872489 0.90182608 0.10825457]]
Max= 0.9960725989589152
np.max= 0.9960725989589152


# Question 2:  matrix norms

In the lectures we focused on the $L^2$-norm. We also briefly mentioned the $L^1$ and $L^\infty$ norm. Let's look at calculating those as well for a general $m\times n$ matrix.

# Q2a

The $L^1$ norm is given by

$$ \lVert A \rVert_1 = \max_j \sum^m_{i=1} |a_{ij}| $$

i.e., it is the max of the sums of the absolute values of each column. Write a function that computes the $L^1$-norm using only loops. The function should use no special numpy functions except `np.abs()`.

In [10]:
def L1Norm(mat):
    s = mat.shape
    cols = s[0]
    rows = s[1]
    colmax = 0
    for row in range(0, rows):
        colsum = 0;
        for col in range(0, cols):
            ele = mat[col,row]
            if ele < 0:
                ele = -ele
            colsum += ele
        if (row == 0) or (colsum > colmax):
             colmax = colsum
    return colmax
    

Check your result against NumPy's `la.norm(A,1)` function for the following random matrix

In [11]:
A = np.random.rand(3,4)
print(A)
print('L1Norm=',L1Norm(A))
print('la.norm=',la.norm(A,1))

[[0.82518476 0.94717488 0.5590027  0.44239937]
 [0.25633983 0.73041276 0.87563928 0.82301787]
 [0.97723729 0.90159765 0.31388852 0.97170007]]
L1Norm= 2.579185290601548
la.norm= 2.579185290601548


## Q2b

The $L^\infty$ norm is given by 

$$\lVert A \rVert_\infty = \max_i \sum_{j=1}^n |a_{ij}|$$

i.e., it is the max of the sums of the absolute values of each row. Write a function that computes the $L^\infty$-norm using only loops and no special numpy functions.

In [12]:
def LInf(mat):
    s = mat.shape
    cols = s[0]
    rows = s[1]
    rowmax = 0
    for col in range(0, cols):
        rowsum = 0;
        for row in range(0, rows):
            ele = mat[col,row]
            if ele < 0:
                ele = -ele
            rowsum += ele
        if (col == 0) or (rowsum > rowmax):
             rowmax = rowsum
    return rowmax
    

Check your result against NumPy's `la.norm(A,np.inf)` function for the following random matrix

In [13]:
A = np.random.rand(3,4)
print(A)
print('LInf=',LInf(A))
print('la.norm(A,np.inf)=',la.norm(A,np.inf))

[[0.70709805 0.26101755 0.27004471 0.19041637]
 [0.892787   0.13116847 0.86692788 0.60147664]
 [0.71357246 0.16422626 0.55670228 0.61009864]]
LInf= 2.492359991389556
la.norm(A,np.inf)= 2.492359991389556


# Question 3: ill-conditions systems of equations

In this question you can use any of NumPy's functions.

## Q3a

Which of the following three matrices, $A1, A2, A3$, are ill-conditioned. State the reason for your conclusion.

In [14]:
A1 = np.array([[0.988746460106, 0.351486109477, 0.024911477532, 0.384039749683],
       [0.282104657306, 0.239884151775, 0.36170151991 , 0.903082266861],
       [0.59333290915 , 0.637178863968, 0.241229214635, 0.685595037901],
       [0.013591747828, 0.917926970364, 0.458689093885, 0.157821121254]])

A2 = np.array([[ 2.852416473483e-01,  3.803483118694e-01,  2.697704226632e-01,  6.810611849029e-01],
       [ 6.622827828376e-01,  6.447943415836e-01,  4.387842058829e-01,  1.530575702376e+00],
       [ 3.672130860703e-01,  8.309522079704e-01,  9.975487474007e-01,  5.678296337101e-01],
       [ 4.036490000599e-01,  6.865978225967e-06,  8.788095913773e-01, -7.150472427928e-02]])

A3 = np.array([[0.131923621844, 0.245316154195, 0.732362341613, 0.957047891764],
       [0.91290446184 , 0.512312007959, 0.391938831444, 0.092509684772],
       [0.648708523652, 0.608576675797, 0.576773587276, 0.065385122929],
       [0.502955480393, 0.084082960221, 0.659487390444, 0.662958739412]])

In [15]:
def ConditionNumber(A):
    return la.norm(A,2)*la.norm(la.inv(A),2)

print("Condition number of A1",ConditionNumber(A1))
print("Condition number of A2",ConditionNumber(A2))
print("Condition number of A3",ConditionNumber(A3))

Condition number of A1 21.552466488381857
Condition number of A2 13334923332.407896
Condition number of A3 15.122449699410629


In [16]:
#Matrix A2 is the most ill-coditioned as it has the largest condirion number of all the matrices.
#Matrix A3 is the least ill-conditioned as it has the condition number closest to one.

# Q3b

With $b = [1,2,3,4]$ and $\delta b = [0.1,0,0,0]$ for $A2$ and $A3$ calculate the percentage change in $x$ due to a small change in $b$, i.e., calculate 

$$100\times\frac{\lVert \delta x_i\rVert_2}{\lVert x_i \rVert_2}\quad\text{and}\quad 100\times\frac{\lVert \delta b\rVert_2}{\lVert b \rVert_2}$$

where $(x_i+\delta x_i)  = A_i^{-1}(b+\delta b)$ and $i\in\{2,3\}$.

In [17]:
b = np.array([1,2,3,4])
db = np.array([0.1,0,0,0])
print("Percentage change in b = ",(la.norm(db,2)/la.norm(b,2))*100)

xdxA2 = la.inv(A2)*(b + db)
xdxA3 = la.inv(A3)*(b + db)

x2 = la.inv(A2)*b
x3 = la.inv(A3)*b

dx2 = xdxA2 - x2
dx3 = xdxA3 - x3

print('Percentage change in x for A2 =', (la.norm(dx2,2)/la.norm(x2,2))*100)
print('Percentage change in x for A3 =', (la.norm(dx3,2)/la.norm(x3,2))*100)

Percentage change in b =  1.8257418583505536
Percentage change in x for A2 = 7.27510078139363
Percentage change in x for A3 = 1.5501828999182938


Which system of equations is more sensitive to small changes in $b$? How could you have guessed this from the answer to the Q3a?

In [18]:
# A2 is more sensitive than A3 to small changes in b.
#This was expected due to the calculated condition numbers from 3a.

# Question 4: eigensystems

In this question we look at finding eigenvalues and eigenvectors

## Q4a

You may use any of NumPy's functions for this sub-question.

Find the eigenvalues and eigenvectors for the below matrix. Print out the eigenvalues sorted by descending value and explicitly show that eigenvalues/eigenvector pairs satisfy $Ax = \lambda x$.

In [19]:
A = np.array([[1,4,5],[4,5,4],[6,7,9]])

In [21]:
eigen = la.eig(A)
values = eigen[0]
vectors = eigen[1]
sortedvalues = np.flip(np.sort(values))
print('Eigenvalue of A = ',la.eig(A))
print("sorted values",sortedvalues)

def EigenvalueConfirmation(Mat, Vec, Val):
    mv = Val*Vec
    mm = Mat.dot(Vec)
    if np.allclose(mm, mv):  # np.equal not suitable as too specific
        print(True)
    else:
        print(False)
        
EigenvalueConfirmation(A,vectors[:,0],values[0])
EigenvalueConfirmation(A,vectors[:,1],values[1])
EigenvalueConfirmation(A,vectors[:,2],values[2])

Eigenvalue of A =  (array([15.78569318, -2.05164645,  1.26595327]), array([[-0.39252008, -0.89589878,  0.09818766],
       [-0.44424151,  0.36255198, -0.77454142],
       [-0.80534308,  0.25675168,  0.6248558 ]]))
sorted values [15.78569318  1.26595327 -2.05164645]
True
True
True


# Q4b

Without using NumPy's `la.eig()` (or similar functions), find the 4 eigenvalues and eigenvectors of the following matrix. Hint: Use the power method for the max eigenvalue (given below in `MaxEigenvalue`), the power method applied to the inverse for the smallest eigenvalue, and apply Hotelling's deflation twice to find the second and third eigenvalues/eigenvectors.

In [22]:
A = np.array([[1.935052353404, 0.887037260957, 1.534235483277, 1.370691224125],
       [0.887037260957, 0.81275989158 , 0.610238622918, 0.999150521052],
       [1.534235483277, 0.610238622918, 1.562260333538, 1.007843062517],
       [1.370691224125, 0.999150521052, 1.007843062517, 1.813258814483]])

In [25]:
def MaxEigenvalue(A, err):
    (m,n) = A.shape
    if(m != n):
        print("Matrix must be square")
        return
    x = np.random.rand(m)
    
    lam = 0.1
    lamprev = 1
    iterations = 0
    while np.abs(1-lam/lamprev) > err:
        Ax = A@x
        lamprev = lam
        lam = la.norm(Ax,2)/la.norm(x,2)
        x = Ax
        iterations += 1
        if(iterations > 1000):
            print('looping...', np.abs(1-lam/lamprev))
            if(iterations > 1010):
                return
    x = x/la.norm(x)
    return (lam,x)

def MinEigenSymmetricPositiveDefinite(A,err):
    (m,n) = A.shape
    if (m != n):
        print('Matrix not square!')
        return
    lmax = MaxEigenvalue(A,err)[0]
    B = A - np.identity(m)*lmax
    eigBmax = MaxEigenvalue(B,err)
    return (-eigBmax[0] + lmax, eigBmax[1])

MaxErr = 1e-5
MaxEigen = MaxEigenvalue(A, MaxErr)
MinEigen = MinEigenSymmetricPositiveDefinite(A, MaxErr)

def Hotelling(A,err):
    MaxEigen = MaxEigenvalue(A, MaxErr)
    MinEigen = MinEigenSymmetricPositiveDefinite(A, MaxErr)
    l1 = MaxEigen[0]
    e1 = MaxEigen[1]
    B = A - l1*np.outer(e1,e1)
    return B

B = Hotelling(A,MaxErr)
C = Hotelling(B,MaxErr)

In [26]:
print('Max Lambda =', MaxEigen)
print('Min Lambda =', MinEigen)
print('Hotelling1 =', MaxEigenvalue(B, MaxErr))
print('Hotelling2 =', MaxEigenvalue(C, MaxErr))

Max Lambda = (4.9148036722209545, array([0.59944659, 0.33322597, 0.49522446, 0.53327008]))
Min Lambda = (0.14437214401625642, array([-0.57123348,  0.62424289,  0.49198944, -0.20484021]))
Hotelling1 = (0.8505815517279447, array([ 0.30706406, -0.38948544,  0.58278702, -0.64371736]))
Hotelling2 = (0.21512741064160767, array([ 0.38296855,  0.67233442, -0.34125584, -0.53370963]))


Check your answers against Numpy's results from `la.eig(A)`

In [27]:
print('Comfirmed Eigenvalues and vectors = ', la.eig(A))

Comfirmed Eigenvalues and vectors =  (array([4.91480442, 0.85058153, 0.14281707, 0.21512836]), array([[ 0.59947641,  0.30724064, -0.63319959, -0.3811686 ],
       [ 0.33318806, -0.3894447 ,  0.53214542, -0.67389895],
       [ 0.49528112,  0.58292464,  0.54707607,  0.34000478],
       [ 0.53320761, -0.64353313, -0.12879172,  0.53382343]]))
